import { Inter } from "next/font/google";
import "../app/globals.css";
import ClientLayout from "./components/ClientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Handcrafted Haven",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href="/favicon-light.ico" media="(prefers-color-scheme: light)" />
                <link rel="icon" href="/favicon-dark.ico" media="(prefers-color-scheme: dark)" />
            </head>
            <body className={inter.className}>
                <ClientLayout>{children}</ClientLayout>
            </body>
        </html>
    );
}
